version: "3.8"

services:

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
      - ai_service
      - qdrant
    # working_dir: /app
    # volumes:
    #   - ./frontend:/app
    # command: ["npm", "run", "build"]
    # environment:
    #   - CI=true

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - ai_service
      - qdrant

  ai_service:
    build: ./ai_service
    container_name: ai_service
    depends_on:
      - redaction_gate

  redaction_gate:
    build: ./redaction_gate
    volumes:
      - ./redaction_gate:/app:z
    depends_on:
      - redaction_db
    ports:
      - "8002:8002"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  redaction_db:
    image: postgres:16
    environment:
      POSTGRES_DB: redaction
      POSTGRES_USER: redact
      POSTGRES_PASSWORD: redact
    volumes:
      - redaction_db_data:/var/lib/postgresql/data

volumes:
  qdrant_data:
  redaction_db_data:

# docker compose up --env-file .env.prod -d --build