version: "3.8"

services:
  ai_service:
    build:
      context: ./ai_service
      dockerfile: Dockerfile.dev
    volumes:
      - './ai_service:/app:z'
    ports:
      - "8001:8001"
    environment:
      - ENV:development
      - DEBUG:True

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    volumes:
      - './backend:/app:z'
    ports:
      - "8000:8000"
    environment:
      - ENV:development
      - DEBUG:True

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    # mount source for live editing but keep container node_modules
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    ports:
      - "3000:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    stdin_open: true
    tty: true

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "8081:80"
  #   volumes:
  #     - ./frontend/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro

# docker compose -f docker-compose.yml -f docker-compose.overwrite.dev.yml up -d --build
# docker compose -f docker-compose.yml -f docker-compose.overwrite.dev.yml down