#  docker-compose.overwrite.dev.yml

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    # mount source for live editing but keep container node_modules
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app:z
    environment:
      # CHOKIDAR_USEPOLLING: true
      NODE_ENV: development
      BACKEND_URL: http://backend:8080
      VITE_API_BASE_URL: http://backend:8080
    stdin_open: true
    tty: true

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    ports:
      - "8000:8080"
    volumes:
      - ./backend:/app:z
    environment:
      - ENV:development
      - DEBUG:True

  ai_service:
    build:
      context: ./ai_service
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8080"
    volumes:
      - ./ai_service:/app:z
    environment:
      - ENV:development
      - DEBUG:True

  redaction_gate:
    build:
      context: ./redaction_gate
      dockerfile: Dockerfile.dev
    ports:
      - "8002:8080"
    volumes:
      - ./redaction_gate:/app:z
    environment:
      - ENV:development
      - DEBUG:True
    # healthcheck:
    #   test: ["CMD", "curl", "-fsS", "http://localhost:8080/healthz"]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 10

# docker compose -f docker-compose.yml -f docker-compose.overwrite.dev.yml --env-file .env.prod up -d --build
# docker compose -f docker-compose.yml -f docker-compose.overwrite.dev.yml down